### ISSUE TITLE
StopTooFarFromShapeValidator throws NPE

### ISSUE THREAD

**Issue by hbruch** [mecatran/gtfsvtor#37] opened 2020-06-11 07:03 UTC
When validating NVBW's [SWEG](https://www.nvbw.de/fileadmin/nvbw/open-data/Fahrplandaten_mit_Liniennetz/sweg.zip) feed, a NPE is thrown, see stacktrace below.

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at com.mecatran.gtfsvtor.validation.impl.CompoundDaoValidator.lambda$validate$1(CompoundDaoValidator.java:54)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.mecatran.gtfsvtor.validation.impl.CompoundDaoValidator.validate(CompoundDaoValidator.java:52)
	at com.mecatran.gtfsvtor.validation.DefaultDaoValidator.validate(DefaultDaoValidator.java:30)
	at com.mecatran.gtfsvtor.lib.GtfsVtor.validate(GtfsVtor.java:84)
	at com.mecatran.gtfsvtor.cmdline.GtfsVtorMain.main(GtfsVtorMain.java:56)
Caused by: java.lang.NullPointerException
	at com.mecatran.gtfsvtor.geospatial.Geodesics.distanceMeters(Geodesics.java:11)
	at com.mecatran.gtfsvtor.dao.impl.InMemoryLinearGeometryIndex.computeShapedWithDistPatternIndex(InMemoryLinearGeometryIndex.java:326)
	at com.mecatran.gtfsvtor.dao.impl.InMemoryLinearGeometryIndex.computePatternIndex(InMemoryLinearGeometryIndex.java:230)
	at com.mecatran.gtfsvtor.dao.impl.InMemoryLinearGeometryIndex.lambda$new$0(InMemoryLinearGeometryIndex.java:127)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.mecatran.gtfsvtor.dao.impl.InMemoryLinearGeometryIndex.<init>(InMemoryLinearGeometryIndex.java:120)
	at com.mecatran.gtfsvtor.dao.impl.InMemoryDao.getLinearGeometryIndex(InMemoryDao.java:352)
	at com.mecatran.gtfsvtor.validation.dao.StopTooFarFromShapeValidator.validate(StopTooFarFromShapeValidator.java:24)
	at com.mecatran.gtfsvtor.validation.impl.CompoundDaoValidator.lambda$validate$0(CompoundDaoValidator.java:47)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
	at com.mecatran.gtfsvtor.geospatial.Geodesics.distanceMeters(Geodesics.java:11)
	at com.mecatran.gtfsvtor.dao.impl.InMemoryLinearGeometryIndex.computeShapedWithDistPatternIndex(InMemoryLinearGeometryIndex.java:326)
	at com.mecatran.gtfsvtor.dao.impl.InMemoryLinearGeometryIndex.computePatternIndex(InMemoryLinearGeometryIndex.java:230)
	at com.mecatran.gtfsvtor.dao.impl.InMemoryLinearGeometryIndex.lambda$new$0(InMemoryLinearGeometryIndex.java:127)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.mecatran.gtfsvtor.dao.impl.InMemoryLinearGeometryIndex.<init>(InMemoryLinearGeometryIndex.java:120)
	at com.mecatran.gtfsvtor.dao.impl.InMemoryDao.getLinearGeometryIndex(InMemoryDao.java:352)
	at com.mecatran.gtfsvtor.validation.triptimes.TooFastTravelValidator.validate(TooFastTravelValidator.java:40)
	at com.mecatran.gtfsvtor.validation.impl.CompoundTripTimesValidator.lambda$validate$1(CompoundTripTimesValidator.java:32)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.mecatran.gtfsvtor.validation.impl.CompoundTripTimesValidator.validate(CompoundTripTimesValidator.java:32)
	at com.mecatran.gtfsvtor.validation.DefaultTripTimesValidator.validate(DefaultTripTimesValidator.java:47)
	at com.mecatran.gtfsvtor.validation.DefaultTripTimesValidator.lambda$scanValidate$1(DefaultTripTimesValidator.java:36)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.mecatran.gtfsvtor.validation.DefaultTripTimesValidator.scanValidate(DefaultTripTimesValidator.java:36)
	at com.mecatran.gtfsvtor.lib.GtfsVtor.validate(GtfsVtor.java:87)
	at com.mecatran.gtfsvtor.cmdline.GtfsVtorMain.main(GtfsVtorMain.java:56)
```

**Comment by hbruch** [comment] 2020-06-11 08:10
The NPE is caused by a stop with coords (0;0) for which [GtfsStop.getCoordinates()](https://github.com/mecatran/gtfsvtor/blame/master/src/main/java/com/mecatran/gtfsvtor/model/GtfsStop.java#L90-L94) returns null. 

I'd prefer to return the (incorrect) (0;0) coord if lat/lon is 0. Even more, as lat/lon are mandatory fields and usually should not be unset, I'd even return (0;0) if they are not given in stop.txt. The StopStreamingValidator would nevertheless report the missing lat/lon values. 

Otherwise, at [InMemoryLinearGeometryIndex](https://github.com/mecatran/gtfsvtor/blob/master/src/main/java/com/mecatran/gtfsvtor/dao/impl/InMemoryLinearGeometryIndex.java#L325) and all other uses of GtfsStop.getCoordinates() would need a null check.

**Comment by laurentg** [comment] 2020-06-11 09:37
For some type of stops (nodes, quays) coordinates are optional, we have to handle this. I agree that returning null if coordinates are (0,0) is not really needed, however most of the client getting coordinates must handle the null case properly, and (0,0) will probably leads to bogus computations so should be taken with care client side (the same remark applies for out-of-bounds values).

I would propose the following if you agree:
- We return (0, 0) coordinates as coordinates, not null in `GtfsStop`.
- We add a "`isCoordinatesValid()`" helper on GtfsStop object that return true if not null, not (0,0) (or other bogus values, like out of bounds). (Or maybe "`getValidCoordinates()`", returning an `Optional<GeoCoordinates>`, or `null`?)
- We fix the code to not throw a NPE by checking is valid before any computation.

**Comment by hbruch** [comment] 2020-06-11 09:52
I agree and would go for `Optional<GeoCoordinates> getValidCoordinates()`. We should remove/deprecate `getCoordinates()` then, I suppose?

**Comment by laurentg** [comment] 2020-06-11 10:18
Yes, we can mark it deprecated first, and remove it step by step later on.

**Comment by hbruch** [comment] 2020-06-11 10:22
Ok, you may assign me, if you'd like to.

**Comment by laurentg** [comment] 2020-06-11 11:28
Thanks! I have a test case ready for that, with filtered data containing the single trip bugging from the SWEG GTFS. I will commit it.

**Comment by laurentg** [comment] 2020-06-11 11:40
For now we should only make sure NPE are not thrown. But in the long term we have to make sure the following case are properly handled and tested regarding shapes:

- Some stop time with missing stop ID or invalid stop ID reference (no stops),
- Some stop time with stop having missing or invalid coordinates.

IE, a single invalid stop time should not invalidate other (valid) stop time linear coordinate indexing (linear index should properly return "invalid" status / values for those stops).

I'm not sure all those cases are part of the unit-test validations. Maybe another issue is needed for those latter (finer) points.

**Comment by hbruch** [comment] 2020-06-11 14:51
Concerning the cases to be addressed long term:

1. missing stop_id currently indeed [seems to be skipped silently](https://github.com/mecatran/gtfsvtor/blob/master/src/main/java/com/mecatran/gtfsvtor/validation/streaming/StopTimeStreamingValidator.java#L52)
2. invalid stop ID [is already reported](https://github.com/mecatran/gtfsvtor/blob/master/src/main/java/com/mecatran/gtfsvtor/validation/streaming/StopTimeStreamingValidator.java#L55-L60) IMHO
3. implementing a missing/invalid coord check for stop times' stops would potentially result in hundreds of reports for the same underlying issue, which already was reported as error for the stop, no? Not sure if this is necessary

**Comment by derhuerst** [comment] 2021-05-18 12:09
I think I've just stumbled across this again, I'm not sure:

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at com.mecatran.gtfsvtor.validation.impl.CompoundDaoValidator.lambda$validate$1(CompoundDaoValidator.java:54)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.mecatran.gtfsvtor.validation.impl.CompoundDaoValidator.validate(CompoundDaoValidator.java:52)
	at com.mecatran.gtfsvtor.validation.DefaultDaoValidator.validate(DefaultDaoValidator.java:30)
	at com.mecatran.gtfsvtor.lib.GtfsVtor.validate(GtfsVtor.java:120)
	at com.mecatran.gtfsvtor.cmdline.GtfsVtorMain.main(GtfsVtorMain.java:56)
Caused by: java.lang.NullPointerException
	at com.mecatran.gtfsvtor.geospatial.Geodesics.distanceMeters(Geodesics.java:11)
	at com.mecatran.gtfsvtor.dao.inmemory.InMemoryLinearGeometryIndex.computeShapedWithDistPatternIndex(InMemoryLinearGeometryIndex.java:304)
	at com.mecatran.gtfsvtor.dao.inmemory.InMemoryLinearGeometryIndex.computePatternIndex(InMemoryLinearGeometryIndex.java:235)
	at com.mecatran.gtfsvtor.dao.inmemory.InMemoryLinearGeometryIndex.lambda$new$0(InMemoryLinearGeometryIndex.java:132)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.mecatran.gtfsvtor.dao.inmemory.InMemoryLinearGeometryIndex.<init>(InMemoryLinearGeometryIndex.java:124)
	at com.mecatran.gtfsvtor.dao.inmemory.InMemoryDao.getLinearGeometryIndex(InMemoryDao.java:462)
	at com.mecatran.gtfsvtor.validation.dao.StopTooFarFromShapeValidator.validate(StopTooFarFromShapeValidator.java:26)
	at com.mecatran.gtfsvtor.validation.impl.CompoundDaoValidator.lambda$validate$0(CompoundDaoValidator.java:47)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
	at com.mecatran.gtfsvtor.geospatial.Geodesics.distanceMeters(Geodesics.java:11)
	at com.mecatran.gtfsvtor.dao.inmemory.InMemoryLinearGeometryIndex.computeShapedWithDistPatternIndex(InMemoryLinearGeometryIndex.java:304)
	at com.mecatran.gtfsvtor.dao.inmemory.InMemoryLinearGeometryIndex.computePatternIndex(InMemoryLinearGeometryIndex.java:235)
	at com.mecatran.gtfsvtor.dao.inmemory.InMemoryLinearGeometryIndex.lambda$new$0(InMemoryLinearGeometryIndex.java:132)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.mecatran.gtfsvtor.dao.inmemory.InMemoryLinearGeometryIndex.<init>(InMemoryLinearGeometryIndex.java:124)
	at com.mecatran.gtfsvtor.dao.inmemory.InMemoryDao.getLinearGeometryIndex(InMemoryDao.java:462)
	at com.mecatran.gtfsvtor.validation.triptimes.TooFastTravelValidator.validate(TooFastTravelValidator.java:41)
	at com.mecatran.gtfsvtor.validation.impl.CompoundTripTimesValidator.lambda$validate$1(CompoundTripTimesValidator.java:31)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.mecatran.gtfsvtor.validation.impl.CompoundTripTimesValidator.validate(CompoundTripTimesValidator.java:31)
	at com.mecatran.gtfsvtor.validation.DefaultTripTimesValidator.validate(DefaultTripTimesValidator.java:47)
	at com.mecatran.gtfsvtor.validation.DefaultTripTimesValidator.lambda$scanValidate$1(DefaultTripTimesValidator.java:36)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.mecatran.gtfsvtor.validation.DefaultTripTimesValidator.scanValidate(DefaultTripTimesValidator.java:36)
	at com.mecatran.gtfsvtor.lib.GtfsVtor.validate(GtfsVtor.java:123)
	at com.mecatran.gtfsvtor.cmdline.GtfsVtorMain.main(GtfsVtorMain.java:56)
```

I use the `laurentgregoire/gtfsvtor` Docker image (image ID is `70e042f1785b`) as follows:

```shell
docker run -i --rm -v $PWD/data/gtfs:/data/gtfs -v $PWD/data/www:/data/www -e TZ=Europe/Berlin -e GTFSVTOR_OPTS=-Xmx29G laurentgregoire/gtfsvtor -o /data/www/gtfsvtor_hbg3.html -p -l 1000 /data/gtfs/hbg3.merged.with_flex.gtfs
```

**Comment by laurentg** [comment] 2021-05-18 12:24
@derhuerst Do you have a sample GTFS that cause this error you can share?

**Comment by derhuerst** [comment] 2021-05-18 14:57
> @derhuerst Do you have a sample GTFS that cause this error you can share?

It's quite big unfortunately: http://116.203.235.64:8002/hbg3.merged.with_flex.gtfs.backup.zip

**Comment by laurentg** [comment] 2021-05-18 16:06
Thanks. That's fine, as long as we can reproduce the issue. We can extract a small sample if needed to add to a test-case later on.

**Comment by derhuerst** [comment] 2021-05-28 15:31
Unfortunately, I have changed the file at this URL by now. 🙈 I will create a new one that reproduces the problem.

**Comment by laurentg** [comment] 2021-05-28 15:37
@derhuerst Did you tried with the latest version? I just tested with your GTFS, it runs fine with master head. If so, I'll make a new release. In all probability your issue has been solved.

**Comment by laurentg** [comment] 2021-05-28 15:39
Ha, our comments crosses each other. Yes, please do, as I am not able to reproduce the issue (although I downloaded your GTFS last week, see checksum below):

```
$ sha1sum hbg3.gtfs.zip 
c24ee66170199c7be484f1e29eb2ccd036f85c78  hbg3.gtfs.zip
```

**Comment by derhuerst** [comment] 2021-05-28 16:40
Can't reproduce it anymore, sorry.

**Comment by laurentg** [comment] 2021-06-02 15:57
No worries, let us know if anything arise again. Closing the issue!

**Closed as completed by laurentg** 2021-06-02 15:57 UTC
Labels: bug
